### ISSUE TITLE
🏁 Windows: `pwd` not available

### ISSUE THREAD

**Issue by shnizzedy** [shnizzedy/cpac#14]
[`pwd`](https://docs.python.org/3.8/library/pwd.html#module-pwd) is not available on Windows, so 

https://github.com/shnizzedy/cpac-python-package/blob/9c3dcd6a2102b49fc7014a50a8043d7e4c97485b/src/cpac/backends/platform.py#L59

won't work on Windows.

**Comment by sgiavasis** [comment]
Can make Windows low priority, at least for now.
(Sorry Windows)

**Comment by shnizzedy** [comment]
Transferred to https://github.com/FCP-INDI/cpac/issues/15
